platform:ios,'9.0'
use_frameworks!
inhibit_all_warnings!

target 'EZBasicKit_Example' do
  pod 'EZBasicKit', :path => '../'

  target 'EZBasicKit_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end

