use_frameworks!

target 'EZBasicKit_Example' do
  pod 'EZBasicKit', :path => '../'

  target 'EZBasicKit_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
    pod 'EZBasicKit', :path => '../'
  end
end
